name: Push to master
on:
  push:
    branches:
      - main
jobs:
  # release:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 15
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v6
  #       with:
  #         fetch-tags: True

      # Determine new version tag
      # NOT CREATED YET

      # Update version in the SlovoVarta.bas
      # - name: Update SlovoVarta.bas with new version
      #   if: steps.tag_version.outputs.new_tag != null
      #   run: |
      #     # Replace `' Version:  1.0.0a` with new version with sed
      #     # Replace `    SlovoVartaVersion = "Slovo-Varta v1.0.0a - Ukrainian Name Declension for Excel"` with new version with sed

      # - name: Commit new version and create tag
      #   if: steps.tag_version.outputs.new_tag != null
      #   id: commit_changes
      #   uses: stefanzweifel/git-auto-commit-action@v7
      #   with:
      #     commit_message: "Release ${{ steps.tag_version.outputs.new_tag }}"
      #     file_pattern: SlovoVarta.bas
      #     branch: main
      #     tag_name: '${{ steps.tag_version.outputs.new_tag }}'
      #     tag_message: 'Release ${{ steps.tag_version.outputs.new_tag }}'
